#PBS -l nodes=2:ppn=28
#PBS -j oe

cd $PBS_O_WORKDIR

inpfile="smiles.txt"
failfile="failed.txt"
smifile='isomers.smi'

name="$(awk '{print $2}' $inpfile)_NMR"
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
ed='\033[0m'

echo -e "${yellow}[$(date +%Y-%m-%d\ %H:%M:%S)]: $name structure enumerate start. ${ed}"
 
# $1 the number of chrial center, $2 the smiles string, $3 nums of center has been replaced
subreplace(){
        if [[ $1 -le $count ]]; then
                subreplace $[$1+1] "$2" "$3"
                subreplace $[$1+1] $(echo $2|sed "s/b/@@/$[$1-$3]") $[$3+1]
        else
                cnt=$[$cnt+1]
                echo "$(echo $2|sed 's/b/@/g') ${name}_$cnt"  >> $smifile
        fi
}

# $1 the smiles string
replace(){
        if [[ "$(echo $1 | grep tC=Ct)" ]]; then
                replace "$(echo $1|sed 's/tC=Ct/\/C=C\\/')"
                replace "$(echo $1|sed 's/tC=Ct/\/C=C\//')"
        elif [[ "$(echo $1 | grep C=Ct)" ]]; then
                replace "$(echo $1|sed 's/C=Ct/C=C\\/')"
                replace "$(echo $1|sed 's/C=Ct/C=C\//')"
        else
                subreplace 1 "$1" 0
        fi
}

# enumerate structure by SMILES format
if [ ! -f $smifile ] || [ ! "$(cat $smifile)" ]; then
        echo -e "${yellow}[$(date +%Y-%m-%d\ %H:%M:%S)]: Getting smi template${ed}"
        cnt=0
        : > $smifile
        SMILES=$(awk '{ gsub(/\/|\\/,"t"); print $1}' $inpfile | awk '{ gsub(/@+/,"b"); print $1}')
        count=$(echo $SMILES| tr -cd 'b' | wc -c)
        if [[ $count -le 1 ]]; then
                echo -e "${yellow}only one conformation${ed}"
                exit
        else
                echo -e "${green}Here are $count chiral carbon, and $(echo $SMILES| tr -cd 't' | wc -c) cis-trans center${ed}"
        fi
        replace "$SMILES"
        if [[ $(awk '!x[$1++]' $smifile|wc -l) -ne $cnt ]]; then
                echo -e "${red}something wrong in enumerate${ed}"
                exit
        else
                echo -e "${green}Here are $cnt conformations${ed}"
        fi
else
        cnt=$(awk '!x[$1++]' $smifile|wc -l)
        echo -e "${green}smifile exist, Here are $cnt conformations${ed}"
fi

echo -e "${yellow}[$(date +%Y-%m-%d\ %H:%M:%S)]: get smiles template finished${ed}"

:>$failfile
for ((i=1;i<=$cnt;i++))
do
        awk 'NR=='$i' {print $0}' $smifile > tmp.smi
        name=$(awk 'NR=='$i' {print $2}' $smifile)
        echo -e "${green}generating ${name}${ed}"
        obabel tmp.smi -oxyz -O struc/${name}.xyz --gen3D -h
        rm tmp.smi
        if [ ! "$(awk '{if($2!=0 && NR>2) x++} END {print x}' struc/${name}.xyz)" ]; then
                echo -e "${red}$i : molecule $name is wrong${ed}"
                awk 'NR=='$i' {print $0}' $smifile >> $failfile
        fi
done

echo -e "${yellow}$(cat $failfile | wc -l) structure wrong${ed}"
echo -e "${yellow}[$(date +%Y-%m-%d\ %H:%M:%S)]: $name structure enumerate finished${ed}"


echo "[$(date +%Y-%m-%d\ %H:%M:%S)] : NMR job start "
:> CNMR.txt
:> HNMR.txt
for file in $(ls struc);
do
        dirname=${file%.*}
        sed -i "2c $dirname" struc/$file
        #obabel struc/$file -osmi >> isomers.smi
        #obabel struc/$file -O inp.xyz --gen3D -h
        cp struc/$file inp.xyz
        if [ ! "$(awk '{if($2!=0 && NR>2) x++} END {print x}' inp.xyz)" ]; then
                echo "molecule $file is wrong"
        else
                ./nmr.sh
                if [[ ! -f TMS.out ]]; then
                        cp $dirname/nmr_result.txt nmr.txt
                        cp $dirname/TMS.out TMS.out
                else
                        cp nmr.txt nmr_0.txt
                        join nmr_0.txt $dirname/nmr_result.txt > nmr.txt
                fi
                awk '{print $2}' $dirname/CNMR.txt | xargs | sed 's/ /,/g' >> CNMR.txt
                awk '{print $2}' $dirname/HNMR.txt | xargs | sed 's/ /,/g' >> HNMR.txt
        fi
done

